### ISSUE TITLE
Create a way to manage the Groovy scripts which will be used in requests

### ISSUE THREAD

**Issue by LCaparelli** [m88i/aicura#6]
We need a way to fetch the Groovy scripts which will be used in requests.

Proposals:

I thought of two approaches for this. Both of them use a repository pattern which would require callers to be aware of the of the desired script's ID. This could be made more user-friendly by adding enum-like constants to provide idiomatic interface (more on this later on).

We'd store each script in a separate file under a dedicated directory, naming them with their ID (e.g., `scripts/1.groovy`).

In both approaches, at this point of development, the repository interface would consist of only two methods, as defined below:

```go
type Script string
type ScriptRepository interface {
	Scripts() ([]Script, error)
	ScriptByID(id int) (Script, error)
}
```

The two mentioned approaches differ on *when* they fetch the scripts.

  1. load a script into memory only when it is requested. This is the slowest but most economic space-wise. Finding the file would take constant time due to the naming scheme being tightly coupled with the script it represents, but loading it from disk will be ultimately slow.
  2.  load all scripts into a slice indexed by their IDs during initialization. This would require reading all files from disk before being able to process any requests, meaning there will be a slower bootstrap time, but as soon as that is done all requests will be processed in O(1) time. This constantly consumes O(n) memory throughout the whole execution. With this approach we would need to decide if we'll watch the files for changes or not (if desired, could be accomplished using [fsnotify](https://github.com/fsnotify/fsnotify)) in order to load the updated scripts into memory.

I personally prefer approach 2, I don't think there will be enough scripts for bootstrap to be affected in a major way. If this changes as the project evolves we can consider different strategies (hopefully wiser and with a deeper understanding of the domain), but for now I believe this is perfectly fine. I also believe watching the script files for changes now is overkill, but we ought to keep that in mind in case we provide users with a mechanism to insert their own scripts in the future (though that would probably render some other changes in the repository's behavior).

In order to make it friendlier to use, we could maintain integer constants which describe the script's functionality so that we don't need to remember a script's ID, only what it does. For example:

```go
const (
	BackupActivityScriptID  = 1
	CountComponentsScriptID = 2
)
```

Callers would then be able to run `repository.ScriptByID(BackupActivityScriptID)`.

Another option is to store scripts with names that reveal something about them and have the repository load them into a map indexed by their file name. This approach could be facilitated by the same enum-like constants, but IMO that only complicates things with little benefit: there's no need for humans to understand what each script does from its file name, they are only there to be processed by the program.

**Comment by ricardozanini** [comment]
That's a nice approach and you did a great job putting together. Unfortunately, the Nexus team is disabling groovy scripts by default in the new versions of the Nexus Server. They are evolving the REST API to offer repositories/backup operations in the `beta` version. We are using this approach instead. Soon, everything will be available at `v1`, so I don't think we need to bother adding groovy support right now to implement the features we need on Nexus Operator.

**Comment by ricardozanini** [comment]
I'm closing this one since we won't implement it for now.

**Comment by ricardozanini** [comment]
See: https://help.sonatype.com/repomanager3/rest-and-integration-api#RESTandIntegrationAPI-ScriptingAPI
